spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/timely_link_demo?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&nullCatalogMeansCurrent=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
  tomcat:
    max-connections: 30000
  resources:
    static-locations: classpath:/static/,classpath:/resources/
    add-mappings: false
  servlet:
    context-path: /timelyFileLink
file:
  path: /Users/test
  ip: http://127.0.0.1
  upload-file: /uploadFile
  file-download-prefix: file



